### ISSUE TITLE
How to install pureseqTM?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pureseqtmr#9]
An email from Cliff Phaneuf:

```
I’m trying to install pureseqTM but am having trouble. That being said, I’m a novice at best at coding/R. When I try to install the package I get the following errors:

> check_pureseqtm_installation

Error: object 'check_pureseqtm_installation' not found

> library(pureseqtmr)

Warning message:

package ‘pureseqtmr’ was built under R version 4.2.2

> check_pureseqtm_installation

function (folder_name = get_default_pureseqtm_folder())

{

    pureseqtm_folder <- file.path(folder_name, "PureseqTM_Package")

    if (!dir.exists(pureseqtm_folder)) {

        stop("Cannot find the PureseqTM folder '", pureseqtm_folder,

            "'\n", "\n", "Tip: from R, run 'install_pureseqtm()'\n")

    }

    testthat::expect_true(dir.exists(pureseqtm_folder))

    bin_filename <- file.path(pureseqtm_folder, "PureseqTM.sh")

    if (!file.exists(bin_filename)) {

        stop("Cannot find the PureseqTM binary at '", bin_filename,

            "'\n", "\n", "Tip: from R, run 'install_pureseqtm()'\n")

    }

    testthat::expect_true(file.exists(bin_filename))

    testthat::expect_true(file.info(bin_filename)$mode != as.octmode("0600"))

}

<bytecode: 0x000001c316e7e818>

<environment: namespace:pureseqtmr>

> install_pureseqtm()

Error: file.exists(bin_filename) is not TRUE

 

`actual`:   FALSE

`expected`: TRUE

 
Do you have any insights as to what I might be doing wrong? Any help would be greatly appreciated.
```

**Comment by richelbilderbeek** [comment]
Hi Clif,

Thanks for your question, I'll happily help you use `pureseqtmr` :-)

First try these:

```r
remotes::install_github("richelbilderbeek/pureseqtmrinstall")
pureseqtmrinstall::install_pureseqtm()
```

Then (add the namespace, i.e. `pureseqtmr::`, so R can find it)(add the `()` at the end, as you want to run the function, not just see it) :

```r
pureseqtmr::check_pureseqtm_installation()
```

This should give you proper help :-) . If not, please hit me with your problems!

Cheers, Richel

**Comment by proteomics-MS** [comment]
Richel,
I was able to install:
remotes::install_github("richelbilderbeek/pureseqtmrinstall")

However, when i try:
pureseqtmrinstall::install_pureseqtm()
I get the following error:
> pureseqtmrinstall::install_pureseqtm()
Error: file.exists(bin_filename) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

Also, when i run:
> library(pureseqtmr)
> pureseqtmr::check_pureseqtm_installation()
i get the error:
Error in pureseqtmr::check_pureseqtm_installation() : 
  Cannot find the PureseqTM binary at 'C:\Users\phacl01\AppData\Local/PureseqTM_Package/PureseqTM.sh'

Any ideas? Sorry for not being much help. I'm trying to install so i can use pureseqtmr in a mass-spectrometry proteomics paper i'm writing.
Thank you so much for helping me-Cliff

**Comment by richelbilderbeek** [comment]
Hmmm, let's take a closer look :-)

First, recreate this error at [https://github.com/richelbilderbeek/pureseqtmr_issue_9](https://github.com/richelbilderbeek/pureseqtmr_issue_9)...

**Comment by richelbilderbeek** [comment]
Hi @proteomics-MS,

Thanks for the report, please keep sharing your problems!

Sadly -in a way- I could not reproduce this bug: running [this R script](https://github.com/richelbilderbeek/pureseqtmr_issue_9/blob/master/script.R) gave [no problems, according to a GitHub Actions log](https://github.com/richelbilderbeek/pureseqtmr_issue_9/actions/runs/4628145051/jobs/8186878524#step:4:1603).

Could you run the R script I used? I copied it below for your convenience :-)

```r
install.packages("remotes")
remotes::install_github("richelbilderbeek/pureseqtmrinstall", dependencies = TRUE)

message("Installing PureseqTM")
pureseqtmrinstall::install_pureseqtm()

message("Check PureseqTM installation")
pureseqtmr::check_pureseqtm_installation()

message("All worked :-)")
```

Thanks and cheers, Richel

**Comment by proteomics-MS** [comment]
Thank you Richel, I was trying to figure out how to recreate the error on github, but I’m not that familiar with that website so I was struggling-sorry

I highlighted an error that may be the reason

The downloaded binary packages are in
               C:\Users\phacl01\AppData\Local\Temp\RtmpO0ZdlB\downloaded_packages
> remotes::install_github("richelbilderbeek/pureseqtmrinstall", dependencies = TRUE)
Skipping install of 'pureseqtmrinstall' from a github remote, the SHA1 (9d7cada3) has not changed since last install.
  Use `force = TRUE` to force installation
> message("Installing PureseqTM")
Installing PureseqTM
> pureseqtmrinstall::install_pureseqtm()
Error: file.exists(bin_filename) is not TRUE

`actual`:   FALSE
`expected`: TRUE

Thank you
Cliff

**Comment by richelbilderbeek** [comment]
Hmm, interesting :thinking: .

Could you run the code below and then try again?

```r
remotes::install_github("richelbilderbeek/pureseqtmrinstall", dependencies = TRUE, force = TRUE)
remotes::install_github("richelbilderbeek/pureseqtmr", dependencies = TRUE, force = TRUE)
```

If that does not work, let's schedule an online meeting, my timezone is Stockholm :-)

**Comment by richelbilderbeek** [comment]
The problem was that `git` was not found in the path, as the user did not install this. In `pureseqtmrinstall`v0.2 this is explicitly check with a -hopefully- helpful error message.

I assume this Issue has been resolved now :-)
